language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to run tests
script:
  - coverage run --source topo setup.py test
before_install:
  - pip install codecov
  - pip install coverage
after_success:
  - codecov
branches:
  only:
    - master