language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to run tests
script: python -m unittest discover
before_install:
  - pip install --user codecov
after_success:
  - codecov
branches:
  only:
    - master